version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Sample-java-app.war:/usr/share/nginx/html/Sample-java-app.war
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tomcat

  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Sample-java-app.war:/usr/local/tomcat/webapps/Sample-java-app.war
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/sampledb
      - DATABASE_USERNAME=sampledb
      - DATABASE_PASSWORD=test123
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=sampledb
      - MYSQL_PASSWORD=test123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
